Fixes #30854 - Move downstream info into defs
theforeman/foreman_maintain pull request #399
Opened 2020-09-16 09:11 UTC by m-bucher

This should ensure that the package-name is definable in the downstream-instance, which might be replaced by configuring a different `definitions`-folder.

I would like to be able to specify an additional package to be upgraded in `perform_self_upgrade()` that should be specified in the upstream-instance, since I install an additional package that holds my custom-definitions folder.
Any ideas how this can be done without changing too much?

2020-09-18 07:51 UTC, upadhyeammit requested changes
As you mentioned you want to upgrade one more package with self upgrade, so in this case are you going to add that change in your fork ? Otherwise what I think is, maybe we can keep the self upgrade package list in metadata file, by default it will have the foreman-maintain package and one can add more. @kgaikwad what you think about this way ?

2020-09-18 07:51 UTC, upadhyeammit commented on lib/foreman_maintain/concerns/downstream.rb
> +      def pkg_and_cmd_name
You can keep pkg_and_cmd_name method in downstream concern only which should serve for both satellite and capsule features. With this I also think we should rename method to something like 'fm_pkg_and_cmd' ?

2020-09-18 07:51 UTC, upadhyeammit commented on lib/foreman_maintain.rb
> +        return instance_feature_downstream.pkg_and_cmd_name
There is typo here it should be `instance_feature.downstream`

2020-09-18 14:20 UTC, m-bucher commented
@upadhyeammit I had not wrapped my head around how to implement the additional-packages feature so we can do this in a separate PR. I can open a separate issue for this.
If you have an idea on how to implement this nicely, please do :-)

2020-09-18 17:47 UTC, kgaikwad commented
> Otherwise what I think is, maybe we can keep the self upgrade package list in metadata file, by default it will have the foreman-maintain package and one can add more. @kgaikwad what you think about this way ?

@upadhyeammit, I didn't get which metadata file you referring here. Could you point me the exact file where you would like to have these changes?

2020-09-22 07:59 UTC, upadhyeammit commented
> > Otherwise what I think is, maybe we can keep the self upgrade package list in metadata file, by default it will have the foreman-maintain package and one can add more. @kgaikwad what you think about this way ?
> 
> @upadhyeammit, I didn't get which metadata file you referring here. Could you point me the exact file where you would like to have these changes?

sorry, I mean data.yml file ? However one can delete this file

2020-09-22 08:41 UTC, kgaikwad commented
> sorry, I mean data.yml file ? However one can delete this file

ahh okies, no problem @upadhyeammit
As per my understanding, foreman-maintain provides a configuration [option](https://github.com/theforeman/foreman_maintain/blob/master/config/foreman_maintain.yml.packaging#L11) to add custom definitions. In similar way, foreman-maintain can have another option to mention package name that provides custom definitions. Accordingly methods i.e `perform_self_upgrade` & `pkg_and_cmd_name` need to be change. 

Needs to check how it will work when a version locking enabled on the system.

2020-09-22 11:16 UTC, m-bucher commented
> As per my understanding, foreman-maintain provides a configuration [option](https://github.com/theforeman/foreman_maintain/blob/master/config/foreman_maintain.yml.packaging#L11) to add custom definitions.

Yes, that is what I am currently using for customization. The config-option `:definitions_dirs` in `/etc/foreman-maintain/foreman_maintain.yml`.

> In similar way, foreman-maintain can have another option to mention package name that provides custom definitions.

Yes, but not in the `/etc/foreman-maintain/foreman_maintain.yml` config-file, but in the class/object derived from `downstream` , which has to be included in the customized `definitions`-directory.
I am pretty sure you meant that, I just wanted to clarify that so we are all on the same page, here :smile:

2020-09-24 06:48 UTC, kgaikwad commented
> Yes, but not in the `/etc/foreman-maintain/foreman_maintain.yml` config-file, but in the class/object derived from `downstream` , which has to be included in the customized `definitions`-directory.

Yes, not using an extra option in `/etc/foreman-maintain/foreman_maintain.yml` config-file. But as @upadhyeammit mentioned `downstream` is very specific to Satellite & Capsule features so class derived from `downstream` would be just a temporary solution. 

My thinking was - if we could add an extra method on `feature` class which will allow user to mention package(s). This way, one can just override this method in his own feature class (here, in your case any custom feature file). 
By default, foreman-maintain will consider either `['rubygem-foreman_maintain', 'foreman-maintain'] or ['satellite-maintain', 'satellite-maintain']` depending upon Satellite/Capsule feature availability. After then it will take into consideration an extra package list from an available features.
But when version locking is enabled then user needs to take care of before adding any extra package(s) into their custom files as we don't have visibility of their custom directories as well as what package values they are going to add. @upadhyeammit, correct me.

BTW, if this needs to be handle in a separate pull-request then current changes looks good to me :+1: :)

@upadhyeammit, @m-bucher, let me know your thoughts on above approach or 
may be we can start discussion on [https://community.theforeman.org/](https://community.theforeman.org/) to get more suggestions?

2020-09-25 09:55 UTC, upadhyeammit commented
> > Yes, but not in the `/etc/foreman-maintain/foreman_maintain.yml` config-file, but in the class/object derived from `downstream` , which has to be included in the customized `definitions`-directory.
> 
> Yes, not using an extra option in `/etc/foreman-maintain/foreman_maintain.yml` config-file. But as @upadhyeammit mentioned `downstream` is very specific to Satellite & Capsule features so class derived from `downstream` would be just a temporary solution.
> 
> My thinking was - if we could add an extra method on `feature` class which will allow user to extend. This way, one can just override this method in his own feature class (here, in your case any custom feature file).
> By default, foreman-maintain will consider either `['rubygem-foreman_maintain', 'foreman-maintain'] or ['satellite-maintain', 'satellite-maintain']` depending upon Satellite/Capsule feature availability. After then it will take into consideration an extra package(s) from an available features to extend list.
> But when version locking is enabled then user needs to take care of before adding any extra package(s) into their custom files as we don't have visibility of their custom directories as well as what package values they are going to add. @upadhyeammit, correct me.
> 
> BTW, if this needs to be handle in a separate pull-request then current changes looks good to me +1 :)
> 
> @upadhyeammit, @m-bucher, let me know your thoughts on above approach or
> may be we can start discussion on https://community.theforeman.org/ to get more suggestions?

Agree ! So having a method in feature class is better idea as in this situation user is already using some custom definitions hence its better to add package name or list to update in that custom definition by extending a method. Apart from that, one would also need to add the required packages in allow-list or whitelist of fm, as self upgrade runs in package locked mode. The current changes looks good to me, and @m-bucher I dont see any better idea to handle this situation. Thank you for contribution !

2020-09-25 10:02 UTC, upadhyeammit approved these changes

2020-09-25 10:05 UTC, merged