Fixes #31951 - f-m online backup to skip /var/lib/pulp/cache
theforeman/foreman_maintain pull request #450
Opened 2021-02-24 08:18 UTC by pmoravec

Signed-off-by: Pavel Moravec <pmoravec@redhat.com>

2021-04-28 10:24 UTC, upadhyeammit commented
Thanks for patience!
Could you move both exclude directories in pulp2 feature and call it in the procedure? something like below,

In file : foreman_maintain/definitions/features/pulp2.rb
~~~
def exclude_for_backup
  ['var/lib/pulp/katello-export', 'var/lib/pulp/cache']
end
~~~

In file: definitions/procedures/backup/pulp.rb
~~~
:exclude => feature(:pulp2).exclude_for_backup,
~~~

2021-04-28 10:25 UTC, upadhyeammit requested changes
Added small change, request to check!
thank you!

2021-04-28 11:02 UTC, pmoravec commented
Thanks for the feedback, good point the change is pulp-2 related only. PR updated.

2021-04-29 09:38 UTC, upadhyeammit requested changes

2021-04-29 09:38 UTC, upadhyeammit commented on definitions/features/pulp2.rb
> +    ['var/lib/pulp/katello-export', 'var/lib/pulp/cache']
The tar command is being run from `/var/lib/pulp` and hence exclude never worked. Request to change method like below,
~~~
def exclude_from_backup
  # Exclude /var/lib/pulp/katello-export and /var/lib/pulp/cache
  %w[katello-export cache]
end
~~~

You will also need to change `feature(:pulp2).exclude_for_backup` to `feature(:pulp2).exclude_from_backup`

2021-04-29 14:15 UTC, pmoravec commented
Sorry for the typos :)

2021-04-30 06:56 UTC, upadhyeammit approved these changes

2021-04-30 06:57 UTC, merged