Fixes #33795 - suggest using f-maintain for z-stream update
theforeman/foreman_maintain pull request #551
Opened 2021-10-27 14:59 UTC by jlsherrill

2021-10-29 18:11 UTC, upadhyeammit requested changes

2021-10-29 18:11 UTC, upadhyeammit commented on definitions/checks/check_for_newer_packages.rb
> +        "#{command} upgrade run --target-version #{@manual_confirmation_version}.z"
The message is too long and doesn't look good, request to modify it something like below,

```suggestion
      fail! 'Required updates for some packages detected.'\
        ""\nPlease update to the latest #{@manual_confirmation_version}.z release "\"\
        'before proceeding, using:'\
        "\n# #{command} upgrade run --target-version #{@manual_confirmation_version}.z"
```

2021-11-02 14:48 UTC, jlsherrill commented
updated!

2021-11-04 11:52 UTC, jlsherrill commented
merging based on evgeni's approval and me addressing amit's comments!

2021-11-04 11:52 UTC, merged