Convert all code to use DNF
theforeman/foreman_maintain pull request #732
Opened 2023-05-20 01:26 UTC by ehelms

2023-07-27 19:24 UTC, ehelms commented
/packit build

2023-09-06 00:47 UTC, ehelms commented
@evgeni When you get a moment, I'd like to get this in at the start of the dev cycle for the next Foreman release.

2023-09-06 09:01 UTC, evgeni requested changes
makes sense overall

2023-09-07 11:27 UTC, evgeni approved these changes

2023-09-07 12:00 UTC, merged