Switch to postgresql 13 module during upgrade after services are stopped
theforeman/foreman_maintain pull request #814
Opened 2024-03-27 13:16 UTC by ehelms

The dnf module switch-to functionality not only swaps module streams but forces the installation of the new packages which can cause the system to be in a bad state. For example, sync plan disable will break in some cases.

I should also mention that it breaks the paradigm we designed where package updates are downloaded but not applied before entering maintenance mode.

2024-03-27 13:19 UTC, evgeni requested changes
You can't enable the `satellite:el8` module as it now has broken deps. That has to happen *after* the switch.
And because if that the download of packages needs to also happen after the switch, as otherwise no packages are downloaded (dnf discards modules with broken deps, and thus all RPMs provided by them)

2024-03-27 13:38 UTC, ehelms commented
> You can't enable the `satellite:el8` module as it now has broken deps. That has to happen _after_ the switch. And because if that the download of packages needs to also happen after the switch, as otherwise no packages are downloaded (dnf discards modules with broken deps, and thus all RPMs provided by them)

I was afraid of that, I hadn't tested this yet. I have another idea but need to test it.

2024-03-27 14:41 UTC, evgeni commented
Yeah, I think you need to move this whole block:
https://github.com/theforeman/foreman_maintain/blob/fba91a5b0548f42a9b10ef70d1e30911692e26c8/definitions/scenarios/upgrade_to_satellite_6_16.rb#L42-L52
down to `Migrations`.

Also, frankly, it makes more sense there. PreMigrations should be non-destructive, while this code (now) is.

2024-03-27 14:56 UTC, evgeni commented on definitions/scenarios/upgrade_to_satellite_6_16.rb
> +      add_step(Procedures::SyncPlans::Disable.new)
Should the same change happen in capsule? OTOH, capsules don't have syncplans.

2024-03-27 15:03 UTC, evgeni commented
I think this should refer to https://projects.theforeman.org/issues/37275 in some way?

2024-03-27 16:12 UTC, ehelms commented
> Yeah, I think you need to move this whole block:
> 
> https://github.com/theforeman/foreman_maintain/blob/fba91a5b0548f42a9b10ef70d1e30911692e26c8/definitions/scenarios/upgrade_to_satellite_6_16.rb#L42-L52
> 
> 
> down to `Migrations`.
> Also, frankly, it makes more sense there. PreMigrations should be non-destructive, while this code is.

I was hoping I could find a way to avoid that :/ since it defeats the whole point of reducing the downtime by caching downloads. Why must modularity break everything.

2024-03-27 16:16 UTC, ehelms commented
Updated to move all of that logic (sadly) into the Migration block after maintenance mode

2024-03-27 18:56 UTC, evgeni commented
you have a typo in the redmine, it's 37275 not 37375 ;)

2024-03-28 13:29 UTC, lpramuk commented
`Upgrade finished.`  

I am able to upgrade after applying this PR

2024-03-28 13:30 UTC, evgeni approved these changes

2024-03-28 23:50 UTC, merged